const SCORE_A = "SCORE_1";
const SCORE_B = "SCORE_B";
const START_MATCH = "START_MATCH"
const MATCH_OVER_A = "MATCH_OVER_A"
const MATCH_OVER_B = "MATCH_OVER_B"
const NEW_MATCH = "NEW_MATCH"

export { SCORE_A, SCORE_B, START_MATCH, MATCH_OVER_A, MATCH_OVER_B, NEW_MATCH }